#ifndef MILESTONES_H
#define MILESTONES_H

// Keep numbers here, helps identifying them and using in data/text/dialogue stuff

enum Milestone {
	MS_OPENING_SCENE = 0,
	MS_TOM_JOINED = 1,
	MS_FISH_JUMPED = 2,
	MS_OPENING_SAVE = 3,
	MS_NO_AUTOSAVE = 4,
	MS_UNDERGROUND_SCENE1 = 5, // right after falling down well
	MS_JB_SHAKE = 6,
	MS_ITEM_DESC_HELP = 7,
	MS_BATTLETUT = 8,
	MS_CAVE1_3_JB_LEAVE = 9,
	MS_CAVE1_5_LEFT = 10,
	MS_CAVE1_5_RIGHT = 11,
	MS_CAVE1_5_COLLAPSE = 12,
	MS_CAVE1_5_COLLAPSE_DONE = 13,
	MS_MENTION_STEAM = 14,
	MS_BOSS1 = 15,
	MS_BOSS1_JB = 16,
	MS_TIK_JOINED = 17,
	MS_TIK_MENTIONED_GEMS = 18,
	MS_GOT_TOKS_GEMS = 19,
	MS_TALKED_ABOUT_BOULDERS = 20,
	MS_BOULDER_RUN_EAST = 21,
	MS_BOULDER_RUN_WEST = 22,
	MS_GREEN_BELTS = 23,
	MS_ELEVATOR_SCENE = 24,
	MS_DID_AN_ATTACK = 25,
	MS_BEAT_CHILLY = 26,
	MS_CAVE3_SCENE = 27,
	MS_CAVE3_JB = 28,
	MS_MET_WIT = 29,
	MS_FOUND_PET_TAG = 30,
	MS_BUMPER = 31,
	MS_END1 = 32,
	MS_END2 = 33,
	MS_SIZE
};

#endif // MILESTONES_H
